FROM deepswe-test-python-summary-base:local

COPY test.sh /tests/test.sh
COPY test.patch /tests/test.patch
COPY grader.py /tests/grader.py
COPY config.json /tests/config.json
RUN chmod +x /tests/test.sh

CMD ["/bin/bash"]
